"""Create tables

Revision ID: dd52ee050cb7
Revises: 
Create Date: 2025-06-27 11:15:27.915387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd52ee050cb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_budgets', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_item', ['user_id', 'budget_item_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_budgets', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_item', type_='unique')

    # ### end Alembic commands ###
